apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret-detection-operator-binding-ClusterRoleBinding.yaml
- secret-detection-operator-role-ClusterRole.yaml
- secret-detection-operator-sa-ServiceAccount.yaml
