apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-detection-operator-binding
  labels:
    app.kubernetes.io/component: rbac
  annotations:
    description: Binds ClusterRole to operator's ServiceAccount
subjects:
  - kind: ServiceAccount
    name: secret-detection-operator
    namespace: secret-detection-system
roleRef:
  kind: ClusterRole
  name: secret-detection-operator
  apiGroup: rbac.authorization.k8s.io
