---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-detection-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - secretdetection.lvlcn-t.dev
  resources:
  - exposedsecrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secretdetection.lvlcn-t.dev
  resources:
  - exposedsecrets/status
  verbs:
  - get
  - patch
  - update
