# Source: secret-detection-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-detection-operator-sa
  labels:
    helm.sh/chart: secret-detection-operator-0.1.0
    app.kubernetes.io/name: secret-detection-operator
    app.kubernetes.io/instance: secret-detection-operator
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    description: Service account used by the Secret Detection Operator.
