# Source: secret-detection-operator/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-detection-operator-binding
  labels:
    helm.sh/chart: secret-detection-operator-0.1.0
    app.kubernetes.io/name: secret-detection-operator
    app.kubernetes.io/instance: secret-detection-operator
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    description: Binds a ClusterRole to the secret detection operator's service account.
subjects:
  - kind: ServiceAccount
    name: secret-detection-operator-sa
roleRef:
  kind: ClusterRole
  name: secret-detection-operator
  apiGroup: rbac.authorization.k8s.io
