# Source: secret-detection-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: secret-detection-operator-service
  labels:
    helm.sh/chart: secret-detection-operator-0.1.0
    app.kubernetes.io/name: secret-detection-operator
    app.kubernetes.io/instance: secret-detection-operator
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: secret-detection-operator
    app.kubernetes.io/instance: secret-detection-operator
