# Source: secret-detection-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-detection-operator
  labels:
    helm.sh/chart: secret-detection-operator-0.1.0
    app.kubernetes.io/name: secret-detection-operator
    app.kubernetes.io/instance: secret-detection-operator
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-detection-operator
      app.kubernetes.io/instance: secret-detection-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-detection-operator
        app.kubernetes.io/instance: secret-detection-operator
    spec:
      serviceAccountName: secret-detection-operator-sa
      securityContext:
        fsGroup: 65532
        supplementalGroups:
          - 65532
      containers:
        - name: secret-detection-operator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsUser: 65532
          image: "ghcr.io/lvlcn-t/secret-detection-operator:v0.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
