# Source: secret-detection-operator/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: secret-detection-operator-servicemonitor
  labels:
    helm.sh/chart: secret-detection-operator-0.1.0
    app.kubernetes.io/name: secret-detection-operator
    app.kubernetes.io/instance: secret-detection-operator
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    description: Monitors the Secret Detection Operator's metrics endpoint.
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-detection-operator
      app.kubernetes.io/instance: secret-detection-operator
  endpoints:
    - port: metrics
      interval: "30s"
